### PR TITLE
Game User Interface

### PR DESCRIPTION
**Pull request by OlawaleJoseph**
This PR implements the user interface of the game.
It prompts the user for input and displays the necessary information and instructions to the players

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

Nice work on this so far.👌

However, let's fix the following:

- [ ] At present your loop would exit when the count reaches 9 but this is not the expected exit condition consider exiting the loop only when the game is over.

- [ ] Also while in the loop kindly ask for the player input, you are presently doing this outside the loop.

- [ ] In addition to a winning move also check if a draw has been reached.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by OlawaleJoseph** [comment]
> ### Hi Team 👋
> Nice work on this so far.👌
> 
> However, let's fix the following:
> 
> * [ ]  At present your loop would exit when the count reaches 9 but this is not the expected exit condition consider exiting the loop only when the game is over.
> * [ ]  Also while in the loop kindly ask for the player input, you are presently doing this outside the loop.
> * [ ]  In addition to a winning move also check if a draw has been reached.
> 
> Kindly fix these issues and request another review👍
> Feel free to contact me on slack(michgolden) if you need further clarification.
> 
> HAPPY CODING👨‍💻

Hi, we are asking for player's input inside the loop. We only ccreated a method responsible for getting the user's input but we call the method in the loop.

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
Hello team, You have ticked all the requirements from the milestone-2. But we have to fix the problem stated by the previous TSE. Let me make it more clear to you. I hope this will help you to understand what needs to be done.
You are checking for a draw and displaying a message which is totally fine but at the same time, you have to terminate the game. Another thing is that we have to check for a winner, if there is a winner, we have to terminate the game. Currently, you are not considering the winner case and it is going to terminate only if there is a draw. Therefore, let's add a conditional statement where you check for a winner as well as draw, and based on that the game will terminate. You do not have to create a working logic to check a winner. You can use boolean for this milestone.

If you need more clarification about the requirement, message me on slack **Suman Shrestha**
**Happy coding !!!**

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
